name: "eBUSd Ventilation"
version: "26.1.6"
slug: ebusd_ventilation
description: "ebusd for the eBUS ventilation bus."
url: https://github.com/zk35-de/ha-addons
arch:
  - amd64
  - aarch64
  - armv7
image: ghcr.io/zk35-de/ebusd-ventilation-{arch}
init: false
startup: services
map:
  - addon_config:rw
services:
  - mqtt:want
uart: true
ports:
  8888/tcp: null
  8889/tcp: null
ports_description:
  8888/tcp: eBUSd TCP command port
  8889/tcp: eBUSd HTTP port (add --httpport=8889 to commandline_options to enable)
ingress: true
ingress_port: 7681
options:
  mqtt_topic: "ventilation"
  mqtt_client_id: ""
  mqtt_int: "standard"
  mqtt_var: "area=Ventilation"
  scan_config: "full"
  poll_interval: 5
  access_level: "*"
  receive_timeout: 100000
  log_level: "all:error"
  commandline_options: []
schema:
  device: "device(subsystem=tty)?"
  network_device: str?
  mqtt_topic: str
  mqtt_client_id: str?
  mqtt_int: str?
  mqtt_var: str?
  scan_config: str?
  poll_interval: int?
  access_level: str?
  receive_timeout: int?
  log_level: str?
  commandline_options:
    - str
